modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Doc-1/Create-Workers/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="create_workers"
    logoFile="create_workers.png"
    version="0.0.1-1.20.1"
    displayName="Create-Workers"
    displayURL="https://github.com/Doc-1/Create-Workers"
    authors="_Doc"
    description='''Example mod description.
Newline characters can be used and will be replaced properly.'''

[[dependencies.create_workers]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_workers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_workers]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.14"

